### ISSUE TITLE
Mastodon icon

### ISSUE THREAD

**Issue by joelisk** [phosphor-icons/homepage#254] opened 2023-04-22 19:49 UTC
**Describe the requested icon**
Icon for Mastodon to connect to social media

**Screenshots**
If applicable, add screenshots to help illustrate the icon appearance.

**Additional context**
https://en.m.wikipedia.org/wiki/File:Mastodon_Logotype_(Simple).svg

**Comment by rektdeckard** [comment] 2023-04-24 07:48
Duplicate of #216

**Closed by rektdeckard** 2023-04-24 07:48 UTC
Labels: enhancement
