### ISSUE TITLE
Brazil wants PIX icon

### ISSUE THREAD

**Issue by AlexShyjada** [phosphor-icons/homepage#285] opened 2023-06-15 12:15 UTC
**Describe the requested icon**
Here in Brazil we use one more payment method: PIX

**Screenshots**
![image](https://github.com/phosphor-icons/homepage/assets/71133582/6c4aa197-8c5d-4bca-a66f-863951b730b0)

**Additional context**
The PIX is an instant payment system developed by the Central Bank of Brazil. Launched in 2020, it enables fast and secure financial transactions, 24 hours a day, 7 days a week. By using basic information such as CPF or cell phone number, users can make payments and transfers easily. The PIX utilizes advanced technology and authentication measures to ensure transaction security.

**Comment by andremourasantos** [comment] 2023-06-26 22:15
It would be awesome if the PIX payment icon is added to the library. As @AlexShyjada described, PIX is an instant payment method launched in 2020 and in just two years has become the [most used payment method in Brazil](https://www.poder360.com.br/economia/pix-e-o-meio-de-pagamento-mais-usado-por-brasileiros-diz-bc/), so it's a pretty important payment method to include in business here.

Here's the [PIX's branding guide](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/I_manual_uso_marca_pix.pdf), I think it could assist with the design or as a source to get some asset. I also found [this site](https://vetores.org/d/pix-banco-central.svg) that has an SVG version of it.

Hope it helps! :P

**Comment by rektdeckard** [comment] 2023-09-18 05:28
Closing as duplicate of #146, but we're looking into it!

**Closed by rektdeckard** 2023-09-18 05:28 UTC
Labels: enhancement
