### ISSUE TITLE
pill bottle

### ISSUE THREAD

**Issue by codysue** [phosphor-icons/homepage#443] opened 2024-03-05 14:59 UTC
**Describe the requested icon(s)**

I work for a healthcare company that utilizes your icon library for system iconography. We have a need for a pill bottle to indicate recent fills and x-month supplies. I do understand that there is an "RX" icon, but this indicates moreso prescriptions as prescribed by your physician and less medications you can get over the counter. i.e. vitamins, anti-inflammatory meds, and things you can get at walgreens, cvs, etc. 

**References**

I've tried to drop, paste and add files to this section but it never succeeds.

**Additional context**

**Comment by rektdeckard** [comment] 2024-03-06 06:08
`pill-bottle` has been added to backlog. Closing as duplicate of #430.

**Closed by rektdeckard** 2024-03-06 06:08 UTC
Labels: icon
