### ISSUE TITLE
Add a "Tractor" icon

### ISSUE THREAD

**Issue by Exylo** [phosphor-icons/homepage#279] opened 2023-06-01 08:55 UTC
**Describe the requested icon**
Usually pictured with a larger wheel on the back, a tractor icon could be usefull in farming-related projects/apps, or to simply communicate anything related to farming / farmers and so on.

**Screenshots**
<img width="444" alt="image" src="https://github.com/phosphor-icons/homepage/assets/10791638/721e2d90-b476-4aea-9d43-8bf4d301c6fa">

**Additional context**
As it's missing in the vehicle pool, a tractor icon would be a nice improvement ! It could be an introduction to farming as a theme, which is often forgotten in icon libraries.

**Comment by rektdeckard** [comment] 2023-09-18 06:14
Closing as duplicate of #260, but we're on it!

**Closed by rektdeckard** 2023-09-18 06:14 UTC
