### ISSUE TITLE
Dashboard Icon

### ISSUE THREAD

**Issue by howdyjules** [phosphor-icons/homepage#634] opened 2024-11-13 09:57 UTC
**Describe the requested icon(s)**

I’m reaching out to see if you could create a dashboard icon. It Could be used for an app next to a navigation item called "Dashboard". 

**Additional context**

Maybe four different sized rectangles representing a dashboard grid?

**Comment by Jamiul-Bari** [comment] 2024-11-16 08:40
how about 'squares-four'

**Comment by rektdeckard** [comment] 2024-12-24 05:05
Duplicate of #617

**Closed by rektdeckard** 2024-12-24 05:05 UTC
Labels: icon
