### ISSUE TITLE
X icon (old Twitter)

### ISSUE THREAD

**Issue by 5t4r-10rd** [phosphor-icons/homepage#362] opened 2023-10-23 10:49 UTC
<img width="48" alt="Screenshot 2023-10-23 134820" src="https://github.com/phosphor-icons/homepage/assets/117113049/12913c71-92e5-446f-a45f-c686706587d8">

**Comment by fergusjames** [comment] 2023-11-02 16:08
Brand toolkit and logo download here: https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by rektdeckard** [comment] 2023-11-02 22:06
Closing as duplicate of #309

**Closed** 2023-11-02 22:07 UTC
Labels: enhancement

**Comment by fergusjames** [comment] 2023-11-03 04:51
@rektdeckard Understood. Am curious why this is "not planned". Is this a principled stand against what has happened at Twitter? Or is it that this needs to await a new version of Phosphor icons?

**Comment by rektdeckard** [comment] 2023-11-03 05:42
@fergusjames it is planned for the next release. Mobile doesn't have an option to close as duplicate, that's all.
