### ISSUE TITLE
add  filter clear icon

### ISSUE THREAD

**Issue by insinfo** [phosphor-icons/homepage#284] opened 2023-06-14 21:24 UTC
add  filter clear icon like 

![image](https://github.com/phosphor-icons/homepage/assets/12227024/5309fe36-036c-4100-b1ec-01f964e24f66)

![image](https://github.com/phosphor-icons/homepage/assets/12227024/f32f4c95-d0a5-4633-a7f4-366e8ad7a404)
![image](https://github.com/phosphor-icons/homepage/assets/12227024/d2e006ea-cc87-43aa-8004-c7a8a5d9e16a)

**Comment by rektdeckard** [comment] 2023-09-18 05:31
Closing as duplicate of #135, but we're on it

**Closed by rektdeckard** 2023-09-18 05:31 UTC
Labels: enhancement
