### ISSUE TITLE
Need for a dial pad button

### ISSUE THREAD

**Issue by eliasalzaghrini** [phosphor-icons/homepage#359] opened 2023-10-21 17:14 UTC
We need a keypad/dial pad icon similar to the phone dialer

[nounNumberPad2150350.pdf](https://github.com/phosphor-icons/homepage/files/13061354/nounNumberPad2150350.pdf)

**Comment by rektdeckard** [comment] 2023-11-19 03:10
Closing as duplicate of #322, dial pad is in the works!

**Closed by rektdeckard** 2023-11-19 03:10 UTC
Labels: enhancement
