### ISSUE TITLE
Mastodon icon

### ISSUE THREAD

**Issue by teseu** [phosphor-icons/homepage#348] opened 2023-10-01 13:09 UTC
**Describe the requested icon**
Since there a new exodus, especially from twitter, mastodon has been more popular every day.

**Screenshots**
An svg file
![mastodon-svgrepo-com](https://github.com/phosphor-icons/homepage/assets/3169307/76fe87a2-ba3c-4f97-9122-fd03e7c1ce04)

**Additional context**
Social media

**Comment by ThatOneCalculator** [comment] 2023-10-01 17:53
Duplicate of #216

**Comment by teseu** [comment] 2023-10-01 19:31
I searched as 'icon', I'll close it now, thanks @ThatOneCalculator .

**Closed** 2023-10-01 19:32 UTC
Labels: enhancement
